# Generated by Django 2.0.4 on 2018-04-18 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0005_auto_20180418_1539'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Info',
            new_name='Info1',
        ),
    ]
