# Generated by Django 2.0.4 on 2018-04-18 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0009_auto_20180418_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans', models.CharField(max_length=32)),
                ('ids', models.CharField(max_length=32)),
                ('score', models.CharField(max_length=32)),
                ('score2', models.CharField(max_length=32)),
                ('timenow', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Infos',
        ),
        migrations.DeleteModel(
            name='Infs',
        ),
    ]
