# Generated by Django 2.0.4 on 2018-04-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0011_auto_20180418_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans', models.CharField(max_length=32)),
                ('ids', models.CharField(max_length=32)),
                ('score', models.CharField(max_length=32)),
                ('timenow', models.DateTimeField(auto_now_add=True)),
                ('ptime', models.CharField(max_length=32)),
                ('psco', models.CharField(max_length=32)),
                ('remark', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='In',
        ),
    ]
