# Generated by Django 2.0.4 on 2018-04-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0012_auto_20180424_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans', models.CharField(max_length=32)),
                ('ids', models.CharField(max_length=32)),
                ('score', models.CharField(max_length=32)),
                ('timenows', models.DateTimeField(auto_now_add=True)),
                ('ptime', models.CharField(max_length=32)),
                ('psco', models.CharField(max_length=32)),
                ('remarks', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='Ins',
        ),
    ]
