# Generated by Django 2.0.4 on 2018-04-24 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0014_infss'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infs',
            name='psco',
        ),
        migrations.RemoveField(
            model_name='infs',
            name='ptime',
        ),
        migrations.RemoveField(
            model_name='infs',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='infs',
            name='score',
        ),
        migrations.RemoveField(
            model_name='infs',
            name='timenows',
        ),
    ]
