# Generated by Django 2.0.4 on 2018-04-24 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0015_auto_20180424_1404'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Infs',
        ),
    ]
